"""add indexes

Revision ID: b98529517204
Revises: f53a5b571443
Create Date: 2026-09-04 00:46:44.575328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98529517204'
down_revision: Union[str, Sequence[str], None] = 'f53a5b571443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_file_id'), 'alerts', ['file_id'], unique=False)
    op.drop_constraint('alerts_file_id_fkey', 'alerts', type_='foreignkey')
    op.create_foreign_key(
        'alerts_file_id_fkey', 'alerts', 'files', ['file_id'], ['id'], ondelete='CASCADE'
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_constraint('alerts_file_id_fkey', 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_file_id_fkey', 'alerts', 'files', ['file_id'], ['id'])
    op.drop_index(op.f('ix_alerts_file_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    # ### end Alembic commands ###
