"""add partial index for stale file reconciliation

Revision ID: c0c0cc658c57
Revises: b98529517204
Create Date: 2026-09-04 02:45:53.723768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c0cc658c57'
down_revision: Union[str, Sequence[str], None] = 'b98529517204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_files_stale', 'files', ['updated_at'], unique=False, postgresql_where=sa.text("processing_status IN ('uploaded', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_stale', table_name='files', postgresql_where=sa.text("processing_status IN ('uploaded', 'processing')"))
    # ### end Alembic commands ###
